### ISSUE TITLE
Not working with Find File

### ISSUE THREAD

**Issue by chookity-pokk** [seagle0128/nerd-icons-ivy-rich#3]
I installed the package and used the config but it seems like I am not able to get it working with find file or describe variable/function/etc. It works with switch to buffer as well as switching perspectives.

Edit:
I tried it with projectile and it worked there and within find file inside of projectile. So am I just having the wrong idea of what the package is doing by chance?

**Comment by seagle0128** [comment]
You should enable `ivy-mode`, and use `counsel-find-file` , `counsel-describe-function`, `counsel-describe-variable`, etc.

**Comment by chookity-pokk** [comment]
Sorry about that. It's been so long since I set up ivy that I genuinely didn't know about most of those counsel commands. Thank you for the help!
